#include<iostream>
#include <algorithm>
using namespace std ;

int main(){

    // char  str[10]={'a','b','c','d','e','f'};

    // cout<<" the answer is "<<int(str[2]);

    // string str;
    // getline(cin,str );

    // for (int i=0;i<str.length();i++){
    //     cout<<str[i]<<" ";

    // }
    // // cout<<str.size() <<" ";
   

    string str1="aplha ";
    string str2="intern ";
    string str3=str1.append(str2);
    // cout <<str1.append(str2);
    // reverse(str3.begin(),str3.end());

    // cout <<str3;

    // cout<<str1.erase(1,3);
    cout <<str3;
    cout <<str3.substr(3,3);


}
 

