#include <iostream>
#include <cstring>
using namespace std;

// int main(){
//    char str[]={ 'a','b','c','d','e','f','\0'};
//    cout<<strlen(str)<<endl;
//    return 0;

// }

// int main (){
//     char str[12];
//     cin.getline(str,100);

//     for (char ch:str){
//         cout<< ch<< " ";
//     }
//     cout << endl;
//     return 0;
// }

// int main(){
//     char str[]="apna college ";
//     int len=0;
//     for (int i=0;i<str[i]!='\0';i++){
//         len++;
//     }
//     cout<< "length of the string is "<< len << endl;
//     return 0;

// }     

// int main(){
//     string str1=" apna college ";
//     string str2="hello world ";
//     string str3=str1+str2;
   
    

    // cout<<st<< " ";
    

// }

// int main(){
    // string  str;
    // getline(cin,str);

    // cout << "output"<< str << endl;

// }

int main(){
    // string str=" apnaa college ";

    // for (int i=0; i<str.length();i++){
    //     cout << str[i]<< endl;
    // }
    // cout<< endl;
    // return 0;


    string str="apna college";

    for (char ch:str){
        cout<<ch <<" "  ;      
    }
    cout<<endl;

}

